### ISSUE TITLE
такая ситуация

### ISSUE THREAD

**Issue by KoSHeroff** [aeonixlegit/PixelX#4]
> Bot started.
(node:1370) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'initPixelCanvas' of undefined
    at PixelBot.startWork (/bot/core.js:122:17)
    at WebSocket.<anonymous> (/bot/core.js:101:16)
    at WebSocket.emit (events.js:210:5)
    at Receiver.receiverOnMessage (/bot/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:210:5)
    at Receiver.dataMessage (/bot/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/bot/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/bot/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/bot/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:431:12)
(node:1370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by Tails-Dev** [comment]
В config.js убрал лишнее?

**Comment by Tails-Dev** [comment]
И посмотри предыдущие ошибки, бот не работает

**Comment by KoSHeroff** [comment]
Если оставить стандартную картинку, то пишет и работает, но с любой моей, поначалу робит, но после падает с такой ошибкой

**Comment by Tails-Dev** [comment]
Скинь config.json

**Comment by KoSHeroff** [comment]
GNU nano 2.5.3                           File: config.json                                                            
{
  "wssLinks": [
    "https://pixel2019.vkforms.ru/ws/21?vk_access_token_settings=&vk_app_id=7148888&vk_are_notifications_enabled=0&vk_i$"(ссылка полная, на телефоне не удобно)
 ],
  "image": "http://school16-zhg.ru/1.png"
}

**Comment by Tails-Dev** [comment]
У меня все сработало
`> Производится запуск [PixelX - github.com/aeonixlegit/PixelX]
> Bot started.
> Image was loaded.
> Pixels was loaded.
> Bot started.
> Connected to WebSocket.
> Установлен пиксель на [1, 1] (21)`

**Comment by aeonixlegit** [comment]
сделал обновление, пробуй, если до сих пор актуально - реопен.
