### ISSUE TITLE
При использовании своей картинки, баг

### ISSUE THREAD

**Issue by KoSHeroff** [aeonixlegit/PixelX#9]
```
> Производится запуск [PixelX - github.com/aeonixlegit/PixelX]
> Производится запуск скрипта.
> Бот запущен.
> Состояние полотна обновлено,
> Шаблон обнолен.
Exception in PromiseRejectCallback:
/bot/core.js:136
  }
  ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/bot/core.js:134
      await this.sendPixel(store)
                 ^

RangeError: Maximum call stack size exceeded
(node:6795) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.split (<anonymous>)
    at PixelBot.sendPixel (/bot/core.js:119:24)
    at PixelBot.sendPixel (/bot/core.js:134:18)
    at PixelBot.sendPixel (/bot/core.js:134:18)
    at PixelBot.sendPixel (/bot/core.js:134:18)
    at PixelBot.sendPixel (/bot/core.js:134:18)
    at PixelBot.sendPixel (/bot/core.js:134:18)
    at PixelBot.sendPixel (/bot/core.js:134:18)
    at PixelBot.sendPixel (/bot/core.js:134:18)
    at PixelBot.sendPixel (/bot/core.js:134:18)
(node:6795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6795) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by KoSHeroff** [comment]
С сток ссылкой работает нормально

**Comment by aeonixlegit** [comment]
Приложи свою картинку, а так - PixelBattle уже завершился, к след. году пофикшу.
